---
- hosts: target_hosts
  become: true
  become_method: su
  vars:
      mc_home: "/opt/MC"
      backup_dir: "~mc/backup_dir"
  tasks:

    - name: upgrade
      apt:
          update_cache: yes
          upgrade: full
    
    - name: install dependencies
      apt:
          name: 
            - git
            - curl
            - procps
            - socat
            - wget
            - zip
            - sudo

    - name: install mcscripts
      git:
          repo: https://github.com/TapeWerm/MCscripts.git
          dest: "/tmp/MCscripts/"

    - name: add mcscripts user
      user:
          name: mc
          home: "{{mc_home}}"
          system: yes
              
    - name: create symbolic link for backup
      file:
          src: ~mc
          dest: "{{backup_dir}}"
          state: link

    - name: mkdir server dir
      file:
          state: directory
          path: "{{item}}"
          recurse: yes
          owner: mc
          group: nogroup
      with_items:
          - ~mc/bedrock
    
    - name: get unit file list
      find:
          paths: /tmp/MCscripts/systemd
      register: unit_files

    - name: copy systemd unit files
      copy:
          src: "{{item.path}}"
          dest: /etc/systemd/system/
          remote_src: yes 
      with_items: "{{unit_files.files}}"

    - name: get script list
      find:
          paths: /tmp/MCscripts
          recurse: no
          patterns: 
              - '*.sh'
              - '*.sed'
      register: mc_scripts
 
    - name: copy .sh scripts
      copy:
          src: "{{item.path}}"
          dest: ~mc/
          group: nogroup
          owner: mc
          mode: 744
          remote_src: yes
      with_items: "{{mc_scripts.files}}"

    - name: check update and get server
      shell: su mc bash -c 'echo y | bash ~/bedrock/MCBEgetZIP.sh'

   - name: update server
     shell: bash ~mc/bedrock/MCBEautoUpdate.sh ~mc/bedrock/MCBE
     register: update_result
     failed_when:
         - update_result.failed == 1
         - "already exists not in {{update_result.msg}}"
  
    - name: change owner of ~mc/bedrock
      file:
          path: ~mc/bedrock
          owner: mc
          group: nogroup
          recurse: yes

    - name: enable server, backup, auto-update
      systemd:
          name: "{{item}}"
          enabled: yes
      with_items:
            - mcbe@MCBE.socket
            - mcbe@MCBE.service
            - mcbe-backup@MCBE.timer
            - mcbe-getzip.timer
   
    - name: start above units
      systemd:
          name: "{{item}}"
          state: started
      with_items:
            - mcbe@MCBE.socket
            - mcbe@MCBE.service
            - mcbe-backup@MCBE.timer
            - mcbe-getzip.timer

  
